### ISSUE TITLE
斯坦福《自然语言处理》课程视频原链接失效

### ISSUE THREAD

**Issue by CSerxy** [ty4z2008/Qix#13]
新链接为：http://cs224d.stanford.edu/syllabus.html

**Comment by ty4z2008** [comment]
已经修正，非常谢谢

**Comment by CSerxy** [comment]
不敢当，我还要谢谢您整理提供了这么多非常好的资料！真的非常难得。

2016-04-10 4:00 GMT-04:00 Jun Liao <notifications@github.com>:

**Comment by ty4z2008** [comment]
@CSerxy 希望能一起参与
