### ISSUE TITLE
要是能把这些材料分下类会好一些

### ISSUE THREAD

**Issue by firogh** [ty4z2008/Qix#15]
RT.

**Comment by ty4z2008** [comment]
Thank you for your follow and issue.
I want to classify this  as standard document ,but i hope someone will help everyone to do it.
can you help us?

**Comment by mutouzhang** [comment]
同求分类 资料收集全面的一塌糊涂 太感动

**Comment by ty4z2008** [comment]
If you can help us to classify.I hope you can contact me .Email:ty4z2008@gmail.com
