### ISSUE TITLE
Machine learning aggregator repos to add

### ISSUE THREAD

**Issue by benedekrozemberczki** [ty4z2008/Qix#33]
Could You add these repositories somehow?

https://github.com/chihming/awesome-network-embedding
https://github.com/benedekrozemberczki/awesome-community-detection
https://github.com/benedekrozemberczki/awesome-community-detection

Bests,

Benedek

**Comment by ty4z2008** [comment]
I already merge. tks🍺

**Comment by benedekrozemberczki** [comment]
Could You add these repositories somehow?

https://github.com/benedekrozemberczki/awesome-fraud-detection-papers
https://github.com/benedekrozemberczki/awesome-decision-tree-papers
https://github.com/benedekrozemberczki/awesome-fraud-detection-papers

Bests,

Benedek

**Comment by ty4z2008** [comment]
> Could You add these repositories somehow?
> 
> https://github.com/benedekrozemberczki/awesome-fraud-detection-papers
> https://github.com/benedekrozemberczki/awesome-decision-tree-papers
> https://github.com/benedekrozemberczki/awesome-graph-embedding
> https://github.com/benedekrozemberczki/awesome-gradient-boosting-papers
> 
> Bests,
> 
> Benedek

Merge done
