### ISSUE TITLE
broken link in db.md

### ISSUE THREAD

**Issue by Deardrops** [ty4z2008/Qix#34]
《分布式系统领域经典论文翻译集》链接已挂
请问哪里有本地离线版本么？

**Comment by stevenlii** [comment]
你试试这个？
分布式系统领域经典论文翻译集 – duanple
http://duanple.com/?p=170

**Comment by Deardrops** [comment]
@stevenlii 感谢😊

**Comment by ty4z2008** [comment]
@Deardrops @stevenlii already merged
