### ISSUE TITLE
Awesome repos

### ISSUE THREAD

**Issue by benedekrozemberczki** [ty4z2008/Qix#38]
Could you add these:

https://github.com/benedekrozemberczki/awesome-gradient-boosting-papers
https://github.com/benedekrozemberczki/awesome-decision-tree-papers
https://github.com/benedekrozemberczki/awesome-monte-carlo-tree-search-papers
https://github.com/benedekrozemberczki/awesome-graph-classification
https://github.com/benedekrozemberczki/awesome-community-detection
https://github.com/benedekrozemberczki/awesome-fraud-detection-papers

And this library:

https://github.com/benedekrozemberczki/karateclub

**Comment by ty4z2008** [comment]
Thanks buddy.

already merge to master
